# Generated by Django 4.0.1 on 2022-01-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.shelter')),
            ],
        ),
    ]
