# Generated by Django 4.0.1 on 2022-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='postcode',
            field=models.CharField(default='CF55FD', max_length=8),
            preserve_default=False,
        ),
    ]
