# Generated by Django 4.0.1 on 2022-01-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelter'),
        ),
    ]
