# Generated by Django 4.0.1 on 2022-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shelter_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
