# Generated by Django 4.0.1 on 2022-01-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_age_pet_bio_pet_gender_pet_species'),
        ('core', '0003_shelter_latitude_shelter_longitude'),
    ]

    operations = [
    ]
